version: "2"
services:
  core:
    container_name: spot4zik-core
    restart: always
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
    - "3000:3000"
    depends_on:
    - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
    - "27017:27017"
